### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by saharNooby** [jagobagascon/Natural-Sorting-for-Java#6]
What versioning scheme does this project use? That is, if I made another pull request, when and how should I increment artifact version?

If no versioning scheme is decided yet, I propose adopting semantic versioning (project already has version in X.Y.Z format): https://semver.org/

SemVer summary:
```
Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards compatible manner, and
3. PATCH version when you make backwards compatible bug fixes.
```

**Comment by jagobagascon** [comment]
This is a really small side project I did years ago, and has been unmaintained since. It provides very little functionality so I never thought it would require any versioning scheme.

SemVer sounds good, but again, I doubt this library will ever include an incompatible API change so the MAJOR version will probably never change.

> when and how should I increment artifact version?
Pull requests should not include a version bump.

This project is not deployed anywhere, I used [jitpack.io](https://jitpack.io/) because it was the simplest option at the moment.  Jitpack checks your GitHub repo tags and creates the jar for you so updating the pom is only necessary when releasing the project (adding a tag to the project).

Now GitHub Packages includes a Maven repository so I might start deploying new versions there. But I would go for something like [semantic release](https://semantic-release.gitbook.io/semantic-release/) to automatically choose the version number based on the commits added to the repository.

**Comment by saharNooby** [comment]
>so I might start deploying new versions there. But I would go for something like semantic release to automatically choose the version number

If automated version management will be used, then there is indeed no need to change version manually.

>Pull requests should not include a version bump.

My first PR did include version bump, so maybe you need to rollback the bumping commit.

I won't change version in my future PRs then. Thanks!
